USE BD_TRAVEL
GO

-- VISUALIZAR SCHEMAS
SELECT * FROM sys.schemas
GO

-- CREANDO SCHEMA MKT

CREATE SCHEMA MKT
GO

-- PRIMARY KEY CLUSTERED
-- AL CREAR UNA TABLA

CREATE TABLE MKT.PAIS (
  ID_PAIS   INT         NOT NULL,
  NOM_PAIS  VARCHAR(50) NOT NULL,
  CONSTRAINT PK_PAIS PRIMARY KEY(ID_PAIS)
)
GO

-- PRIMARY KEY NONCLUSTERED
-- SOBRE UNA TABLA EXISTENTE

CREATE TABLE MKT.TIENDA (
  ID_TIENDA   INT           NOT NULL,
  NOM_TIENDA  VARCHAR(50)   NOT NULL,
  DIR_TIENDA  VARCHAR(60)   NOT NULL
)
GO

ALTER TABLE MKT.TIENDA
  ADD CONSTRAINT PK_TIENDA
  PRIMARY KEY NONCLUSTERED (ID_TIENDA)
GO

-- FOREIGN KEY
-- AL CREAR UNA TABLA

CREATE TABLE MKT.CLIENTE (
  ID_CLI   CHAR(5)       NOT NULL,
  NOM_CLI  VARCHAR(50)   NOT NULL,
  ID_PAIS  INT           NOT NULL
  CONSTRAINT FK_PAIS_CLIENTE  FOREIGN KEY (ID_PAIS)
  REFERENCES MKT.PAIS
)
GO

-- FOREIGN KEY
-- AL CREAR UNA TABLA EXISTENTE
-- USANDO ELIMINACION EN CASCADA

CREATE TABLE MKT.PROVEEDOR (
  ID_PROVE   CHAR(5)       NOT NULL,
  NOM_PROVE  VARCHAR(40)   NOT NULL,
  ID_PAIS    INT           NULL
  CONSTRAINT FK_PAIS_PROVE  FOREIGN KEY (ID_PAIS)
  REFERENCES MKT.PAIS
  ON DELETE CASCADE -- Elimina registros dependientes al PK
)
GO

-- FOREIGN KEY
-- SOBRE UNA TABLA EXISTENTE

CREATE TABLE MKT.EMPLEADO (
  COD_EMP    CHAR(5)       NOT NULL,
  NOM_EMP    VARCHAR(50)   NOT NULL,
  ID_TIENDA  INT           NULL
)
GO

ALTER TABLE MKT.EMPLEADO
  ADD CONSTRAINT FK_TIENDA_EMP FOREIGN KEY (ID_TIENDA)
  REFERENCES MKT.TIENDA
  ON UPDATE CASCADE -- Actualiza registros dependientes al PK
GO

-- UNIQUE
-- AL CREAR UNA TABLA

CREATE TABLE MKT.CONDUCTOR (
  COD_COND   CHAR(5)      NOT NULL,
  NOM_COND   VARCHAR(50)  NOT NULL,
  APE_COND   VARCHAR(50)  NOT NULL,
  BRV_COND   CHAR(10)     NOT NULL,
  CONSTRAINT UQ_BREVETE  UNIQUE (BRV_COND)
)
GO

-- UNIQUE
-- SOBRE UNA TABLA EXISTENTE

ALTER TABLE MKT.CONDUCTOR
  ADD CONSTRAINT UQ_NOM_AP_COND
  UNIQUE (NOM_COND, APE_COND)
GO

-- DEFAULT
-- AL CREAR UNA TABLA

CREATE TABLE MKT.POSTULANTE (
  COD_POS   CHAR(5)      NOT NULL,
  NOM_POS   VARCHAR(50)  NOT NULL,
  ECI_POS   VARCHAR(30) 
    CONSTRAINT DF_CIVIL_POS DEFAULT 'SOLTERO',
  FRE_POS   DATE
)
GO

-- DEFAULT
-- SOBRE UNA TABLA EXISTENTE

ALTER TABLE MKT.POSTULANTE
  ADD CONSTRAINT DF_FECH_REGISTRO_POS
  DEFAULT GETDATE() FOR FRE_POS
GO

-- CHECK
-- AL CREAR UNA TABLA

CREATE TABLE MKT.PRODUCTO (
  COD_PRO   CHAR(5)      NOT NULL,
  NOM_PRO   VARCHAR(50)  NOT NULL,
  FEP_PRO   DATE         NOT NULL,
  FEV_PRO   DATE         NOT NULL,
  PRE_PRO   SMALLMONEY   NOT NULL,
  CONSTRAINT CK_COD_PRO CHECK
    (COD_PRO LIKE 'P[0-9][0-9][0-9][0-9]')
)
GO

-- CHECK
-- SOBRE UNA TABLA EXISTENTE

ALTER TABLE MKT.PRODUCTO
  ADD 
  CONSTRAINT CK_FEC_VENCIMIENTO_PRO
    CHECK (FEV_PRO > FEP_PRO),
  CONSTRAINT CK_PRE_PRODUCTO
    CHECK (PRE_PRO > 0)  
GO

-- CHECK
-- SOBRE UNA TABLA EXISTENTE
-- NO APLICANDO COMPROBACION DE REGLA A DATOS EXISTENTES

ALTER TABLE MKT.PRODUCTO WITH NOCHECK
 ADD
 CONSTRAINT CK_FEC_PRODUCCION_PRO
   CHECK (FEP_PRO >= GETDATE())
GO

-- DESHABILITAR CHECK

ALTER TABLE MKT.PRODUCTO
  NOCHECK CONSTRAINT CK_COD_PRO
GO

-- HABILITAR CHECK

ALTER TABLE MKT.PRODUCTO
  CHECK CONSTRAINT CK_COD_PRO
GO


/*  VISUALIZAR RESTRICCIONES CREADAS  */

SELECT * FROM sys.check_constraints   -- CHECK
SELECT * FROM sys.key_constraints     -- KEY - UQ
SELECT * FROM sys.default_constraints -- DEFAULT
GO

-- ELIMINAR RESTRICCIÓN

ALTER TABLE MKT.PRODUCTO
  DROP CONSTRAINT CK_COD_PRO
GO

-- IDENTITY

CREATE TABLE MKT.TICKET (
  NRO_TICKET   INT  IDENTITY (1000,1), -- (Inicio, Incremento)
  FEX_TICKET   DATETIME,
  FEV_TICKET   DATETIME,
  NOM_EVENTO   VARCHAR(50),
  VAL_TICKET   SMALLMONEY
)
GO

-- RESETEAR IDENTITY

DBCC CHECKIDENT ('MKT.TICKET', RESEED, 2000)
GO

-- VISUALIZAR CAMPOS IDENTITY

SELECT * FROM sys.identity_columns
GO

-- DESACTIVAR IDENTITY

SET IDENTITY_INSERT BD_TRAVEL.MKT.TICKET ON
GO

-- INSERTAR REGISTRO INCLUSO CAMPO IDENTITY

INSERT MKT.TICKET (NRO_TICKET, FEX_TICKET, FEV_TICKET, NOM_EVENTO, VAL_TICKET) VALUES
  (6666, GETDATE(), GETDATE() + 1, 'CONC PHILL COLL', '200')
GO

SELECT * FROM MKT.TICKET
GO