USE master
GO

-- POR DEFECTO
CREATE DATABASE BD_CONTOSO
GO

-- PERSONALIZADA
CREATE DATABASE BD_TRAVEL
ON (
  NAME = TRAVEL_DATA,
  FILENAME = 'C:\Data\TRAVEL_DATA.MDF',
  SIZE = 5MB,
  MAXSIZE = 50MB,
  FILEGROWTH = 25%
)
LOG ON (
  NAME = TRAVEL_LOG,
  FILENAME = 'C:\Data\TRAVEL_LOG.LDF',
  SIZE = 5MB,
  MAXSIZE = 150MB,
  FILEGROWTH = 5MB
)
GO

-- ACTUALIZANDO ARCHIVOS

ALTER DATABASE BD_TRAVEL
MODIFY FILE (
  NAME = TRAVEL_DATA,
  MAXSIZE = 450MB
)
GO

-- AGREGAR ARCHIVOS

ALTER DATABASE BD_TRAVEL
ADD FILE (
  NAME = TRAVEL_DATAN1,
  FILENAME = 'C:\Data\TRAVEL_DATAN1.NDF'
)
GO