USE master
GO

/*

En la empresa Recobra, se decidió implementar una Tabla
particionada para almacenar sus solicitudes y poder optimizar
las consultas por trimestre de cualquier año, por un tema de
análisis comparativo.

*/

-- 1. Crear los filegroups.

ALTER DATABASE BD_RECOBRA
  ADD FILEGROUP FG_TRIMESTRE1
GO

ALTER DATABASE BD_RECOBRA
  ADD FILEGROUP FG_TRIMESTRE2
GO

ALTER DATABASE BD_RECOBRA
  ADD FILEGROUP FG_TRIMESTRE3
GO

ALTER DATABASE BD_RECOBRA
  ADD FILEGROUP FG_TRIMESTRE4
GO


-- 2. Adicionar los datafiles.

ALTER DATABASE BD_RECOBRA
ADD FILE(
  NAME = DATA_TRIMESTRE1,
  FILENAME = 'C:\Data\DATA_TRIMESTRE1.NDF'
) TO FILEGROUP FG_TRIMESTRE1
GO

ALTER DATABASE BD_RECOBRA
ADD FILE(
  NAME = DATA_TRIMESTRE2,
  FILENAME = 'C:\Data\DATA_TRIMESTRE2.NDF'
) TO FILEGROUP FG_TRIMESTRE2
GO

ALTER DATABASE BD_RECOBRA
ADD FILE(
  NAME = DATA_TRIMESTRE3,
  FILENAME = 'C:\Data\DATA_TRIMESTRE3.NDF'
) TO FILEGROUP FG_TRIMESTRE3
GO

ALTER DATABASE BD_RECOBRA
ADD FILE(
  NAME = DATA_TRIMESTRE4,
  FILENAME = 'C:\Data\DATA_TRIMESTRE4.NDF'
) TO FILEGROUP FG_TRIMESTRE4
GO

-- 3. Crear la Función de Partición.

USE BD_RECOBRA
GO

CREATE PARTITION FUNCTION FNP_TRIMESTRE(TINYINT)
AS RANGE LEFT
  FOR VALUES (3,6,9)
GO

-- 4. Crear el esquema de Partición.

CREATE PARTITION SCHEME SCH_TRIMESTRE
AS PARTITION FNP_TRIMESTRE
  TO ('FG_TRIMESTRE1','FG_TRIMESTRE2','FG_TRIMESTRE3','FG_TRIMESTRE4')
GO

-- 5. Crear la tabla Particionada

CREATE TABLE dbo.TB_SOLICITUD (
  NRO_SOL   INT          NOT NULL,
  TIT_SOL   VARCHAR(50)  NOT NULL,
  FECH_SOL  DATE         NOT NULL,
  TRIM_SOL  TINYINT      NOT NULL
) ON SCH_TRIMESTRE(TRIM_SOL)
GO
