USE BD_TRAVEL
GO

-- CREACION DE SCHEMAS

CREATE SCHEMA VENTAS
GO

CREATE SCHEMA RRHH
GO

-- VISUALIZAR SCHEMAS CREADOS

SELECT * FROM sys.schemas
GO

-- ELIMINAR SCHEMA

CREATE SCHEMA MKT
GO

DROP SCHEMA MKT
GO

-- CREACION DE TIPOS DE DATO 1

SP_ADDTYPE FONO, 'VARCHAR(15)', 'NULL'
GO

SP_ADDTYPE GENERO, 'CHAR(1)', 'NOT NULL'
GO

-- CREACION DE TIPOS DE DATO 2

CREATE TYPE TIEMPO FROM DATETIME NOT NULL
GO

-- ELIMINAR TIPO DE DATO 1

SP_DROPTYPE GENERO
GO

-- ELIMINAR TIPO DE DATO 2

DROP TYPE TIEMPO
GO

-- CREAR TIPO DE DATO TABLA

CREATE TYPE TCLIENTE AS TABLE (
  NOM_CLI	  VARCHAR(100)	NOT NULL,
  APE_CLI	  VARCHAR(100)	NOT NULL,
  EMAIL_CLI	  VARCHAR(100)	NOT NULL
)
GO

-- UTILIZANDO TIPO DATO TABLA

DECLARE @V_TablaCli TCLIENTE -- Se crea variable
INSERT @V_TablaCli VALUES -- Se inserta datos a la variable
  ('Juan', 'Alva', 'abc@yahoo.com'),
  ('Luis', 'Rios', 'lrios@gmail.com'),
  ('Carlos','Perez','cp@hotmail.com')
SELECT * FROM @V_TablaCli -- Visualizar información
GO
