USE BD_TRAVEL
GO

-- VISUALIZAR TODOS LOS SCHEMAS

SELECT * FROM sys.schemas
GO

-- VISUALIZAR INFORMARCION DE LA BD Y FILEGROUPDS

SP_HELPDB BD_TRAVEL
GO

-- CREACION DE UNA TABLA CON SCHEMA Y FILEGROUP

CREATE TYPE TIEMPO FROM DATETIME NOT NULL -- tipo TIEMPO
GO

CREATE TABLE RRHH.TB_EMPLEADO (
  COD_EMP	  CHAR(5)       NOT NULL,
  NOM_EMP	  VARCHAR(40)   NOT NULL,
  FIN_EMP	  TIEMPO        NOT NULL,
  SUELD_EMP	  SMALLMONEY    NOT NULL
) ON FG_ADMINISTRA
GO

-- VISUALIZAR ESTRUCTURA DE UNA TABLA

SP_HELP 'RRHH.TB_EMPLEADO'
GO

-- AGREGAR COLUMNAS A UNA TABLA

ALTER TABLE RRHH.TB_EMPLEADO 
  ADD TELEF_EMP   VARCHAR(14)  NOT NULL,
      DIR_EMP     VARCHAR(100) NOT NULL
GO

-- MODIFICAR PROPIEDAD DE UN CAMPO EN UNA TABLA

ALTER TABLE RRHH.TB_EMPLEADO
  ALTER COLUMN
    TELEF_EMP  INT  NOT NULL
GO

-- ELIMINAR UN CAMPO DE UNA TABLA

ALTER TABLE RRHH.TB_EMPLEADO
  DROP COLUMN TELEF_EMP, DIR_EMP
GO

-- ADICIONANDO UN CAMPO CALCULADO A UNA TABLA

ALTER TABLE RRHH.TB_EMPLEADO
  ADD SERV_YEARS_EMP AS DATEDIFF(YY, 2030, GETDATE())
GO

/*
    MANEJO DE TABLAS PARTICIONADAS
*/

-- 1. CREAR FILEGROUPS

USE master
GO

ALTER DATABASE BD_TRAVEL
  ADD FILEGROUP FG001
GO

ALTER DATABASE BD_TRAVEL
  ADD FILEGROUP FG002
GO

ALTER DATABASE BD_TRAVEL
  ADD FILEGROUP FG003
GO

-- 2. ADICIAR DATAFILE A SU RESPECTIVO FILEGROUP

ALTER DATABASE BD_TRAVEL
ADD FILE (
  NAME = DATAP01,
  FILENAME = 'C:\Data\DATAP01.NDF'
) TO FILEGROUP FG001
GO

ALTER DATABASE BD_TRAVEL
ADD FILE (
  NAME = DATAP02,
  FILENAME = 'C:\Data\DATAP02.NDF'
) TO FILEGROUP FG002
GO

ALTER DATABASE BD_TRAVEL
ADD FILE (
  NAME = DATAP03,
  FILENAME = 'C:\Data\DATAP03.NDF'
) TO FILEGROUP FG003
GO

-- 3. CREACION DE UNA FUNCION DE PARTICION

USE BD_TRAVEL
GO

CREATE PARTITION FUNCTION FNP_NUMERADOR(INT)
AS RANGE LEFT
  FOR VALUES (2000,4000)
GO

-- 4. CREACION DEL ESQUEMA DE PARTICION

CREATE PARTITION SCHEME SCP_NUMERADOR
AS PARTITION FNP_NUMERADOR
  TO ('FG001','FG002','FG003')
GO

-- 5. CREACION DE LA TABLA PARTICIONADA

CREATE TABLE VENTAS.TB_VENTA (
  ID_VENT    INT         NOT NULL,
  FECH_VENT  DATE        NOT NULL,
  VAL_VENT   SMALLMONEY  NOT NULL
) ON SCP_NUMERADOR (ID_VENT)
GO

-- 6. VERIFICAR FUNCIONAMIENTO TABLA PARTICIONADA

INSERT VENTAS.TB_VENTA VALUES
  (1001, '2000-12-10', '5500'),
  (2010, '2010-10-10', '6500'),
  (4015, '2015-02-21', '3500')
GO

SELECT * FROM VENTAS.TB_VENTA
GO

SELECT *, $PARTITION.FNP_NUMERADOR(ID_VENT) AS [Nro Partición]
  FROM VENTAS.TB_VENTA
GO