USE BD_TRAVEL
GO

-- VERIFICAR TABLAS DISPONIBLES EN LA BD

SELECT * FROM sys.tables
GO

-- VERIFICAR LA ESTRUCTURA DE LA TABLA

SP_HELP 'MKT.CLIENTE' 
GO

-- USANDO BD NORTHWIND

USE Northwind
GO

-- INGRESANDO DATOS A UNA TABLA DESDE OTRA TABLA DE OTRA BD

USE BD_TRAVEL
GO

INSERT logistic.TBProveedor
SELECT CompanyName, ContactName, City, Country
FROM Northwind.dbo.Suppliers
GO